version: "3.3"
services:
  server:
    build:
      context: ./back
    container_name: back
    volumes:
     - ./back:/code
    restart: always
    ports:
      - "8080:8080"
    networks:
       - appnet
  redis:
     image: redis:latest
     container_name: redis_db
     ports:
      - "6379:6379"
     restart: always
     volumes:
      - ./docker/data:/data
     environment:
        - REDIS_ROOT_PASSWORD="secret"
     networks:
       - appnet
networks:
  appnet:
    driver: bridge
